### ISSUE TITLE
Create pipes continue to drain from drawer that's not actually connected

### ISSUE THREAD

**Issue by mcm** [joe-vettek/Fluid-Drawers-Legacy#18]
## Game Version, Launcher Version, Mod Version

MC 1.20.1

Forge 47.2.0

Fluid Drawers Legacy 4.1.4-hotfix

## Problem Description

Sorry for reporting another so soon, thanks again for the quick fix on the last one! When setup as such:

![2024-02-12_23 09 08](https://github.com/joe-vettek/Fluid-Drawers-Legacy/assets/4228826/4757ad8a-4b95-4c00-9bab-204d16819534)

Everything works as expected. However, after breaking the drawer trim like so:

![2024-02-12_23 10 05](https://github.com/joe-vettek/Fluid-Drawers-Legacy/assets/4228826/0aedb978-8627-47ee-ad3a-5bc3a88a57bc)

The pipes will continue to pull from the fluid drawer, even though its no longer connected. That is, if i right click the drawer with a lava bucket, it shows 1B and then drains into the tank on the right, which goes up by 1 bucket.

I'm also having an issue where fluids are getting pumped into a drawer network but seem to be disappearing, still trying to figure out what's happening and how to recreate it though. Not sure if its related to this or not.

**Comment by joe-vettek** [comment]
thanks for your testing findings. and what you said is indeed a problem.  
Let's discuss the first one. The mechanism of the Storage Drawer is to rebuild the drawer network every five seconds (5s, not exactly sure). The fluid drawer will also be connected to this network, and therefore can be used as an additional capability to allow the drawer controller or slave to output fluid. So if this only lasts a few seconds, it's normal.

If it takes too long, for example, it still works after one minute, then may need to re-examine this mechanism, because one possible situation is that the pump is constantly requesting every game moment, which will prevent the fluid drawer network from  reconstruction.

**Comment by joe-vettek** [comment]
I think I should probably delete my previous tirade, lol. After careful inspection of the code, I confirmed the problem. This is also a hidden vulnerability, although it may be harmless (relocating the Slave will solve the problem). The reason for the problem is that the current version of Slave still holds the drawer controller information, and I must also check whether the Slave is in the record of the drawer controller. Well, to be honest I wasn't expecting this design pattern.

**Comment by joe-vettek** [comment]
I uploaded a beta version, you can see it on Curseforge.
[File Link](https://www.curseforge.com/minecraft/mc-mods/fluid-drawers-legacy/files/5104124)

**Comment by mcm** [comment]
Thanks again for the quick fix! I tested this real quick in a creative world and it seems to have fixed the disconnected drawer issue. I'll get on my server tonight and make sure its working there, and keep trying to recreate the issue I'm having with fluids disappearing

**Comment by joe-vettek** [comment]
ohno, I found a big problem. I should have figured out why the fluid was disappearing, it looks like I'll have to pull back the latest release.
One of the Cyclic Mod and Create Mod uses the wrong fluid request method.
Cyclic keeps sending simulated actions, while Create sends simulated action first and then excuted action. Considering that the download volume of Cyclic is not low, I feel that this problem is a bit of a headache.

**Comment by joe-vettek** [comment]
One of the Cyclic Mod and Create Mod uses the wrong fluid delivery method.

**Comment by joe-vettek** [comment]
I can only say that this problem is rather strange. If there is fluid in two drawers, only 1/2 will be left after being pulled out by Create pump, but if there is only one, it will not.
![image](https://github.com/joe-vettek/Fluid-Drawers-Legacy/assets/82761814/9ce7cdcf-6ae4-4089-bd64-8a9c6328ab26)

**Comment by joe-vettek** [comment]
I thought maybe I should call the developers of Create.
![image](https://github.com/joe-vettek/Fluid-Drawers-Legacy/assets/82761814/a34f51c8-0763-4e16-ac0b-a284cc3b3091)
I set FluidAction (divided into EXECUTE, SIMULATE) to directly return a null value in the case of EXECUTE. As a result, guess what, the pump can still pump out liquid.
Then I went to study the source code and found that the code written by Code is very magical.
When extracting fluid, if there are multiple tanks, then if the first tank extracts fluid and the second tank extracts it as empty, it will be directly overwritten. Then enter the following if to determine if it is true, and draw it again directly, but the output is only the amount once.
![image](https://github.com/joe-vettek/Fluid-Drawers-Legacy/assets/82761814/a3c708ce-2255-4052-8b36-110acdbb31b9)

**Comment by joe-vettek** [comment]
[com.simibubi.create.content.fluids.FluidNetwork](https://github.com/Creators-of-Create/Create/blob/2201d87da7744cf9ee3f83e1e4c21643244f342b/src/main/java/com/simibubi/create/content/fluids/FluidNetwork.java#L196)

**Comment by joe-vettek** [comment]
After discussions with some modders, a fluid interface solution was finally redesigned to adapt to Create's code, which will abstract the tank concept (in the past, a fluid drawer network was established based on physical structures). Although there will be very little traffic loss in early tests, in the current version, even if it is induced according to the past plan, it still performs normally. Of course this still needs further verification.
![image](https://github.com/joe-vettek/Fluid-Drawers-Legacy/assets/82761814/91e3387e-e915-4b0b-bdbf-2fc29055349e)

**Comment by mcm** [comment]
Awesome! I'm happy to do some testing if you need as well.

**Comment by joe-vettek** [comment]
thank you. the file has been uploaded to curseforge yet
[FluidDrawersLegacy-1.20.1-forge-4.1.6-beta.jar](https://www.curseforge.com/minecraft/mc-mods/fluid-drawers-legacy/files/5105968)
This version is marked as release when uploaded and will be changed back to beta later.

**Comment by mcm** [comment]
Testing with 4.1.6 i still have issues where fluid is getting pumped into a controller and seems to be disappearing... it only happens when i have a drawer placed that's working and then move it, it seems... but once i pick up the drawer, the fluid keeps getting pumped into the controller and going nowhere.

There's also an issue where the fluid isn't getting pumped into the drawer even when its connected to the network. This seems like it might be dependent on how far the drawer is from the controller, though. It's close enough that controller slaves still see other drawers on the network. I do have the range turned up in the Storage Drawers config if that matters.

I see though that you're working on 4.1.7 so I'll test that once it's available.

**Comment by mcm** [comment]
Also I have no idea if this is related or not, so just mentioning it here in case it is... I have Jade installed, and when I look at the drawers I see the correct fluid (in this case, Awkward Potion and Potion of Strength) and correct quantity on each drawer, but when I look at the controller slave I see "Uncraftable Potion" and its the combined amount of the two potions.

**Comment by joe-vettek** [comment]
The simple test in version 4.1.7 has not been able to reproduce it yet, but Create's pump may need a wrench to reset the direction (sometimes it gets stuck).
The second thing you said should be fixed in 4.1.7.
![image](https://github.com/joe-vettek/Fluid-Drawers-Legacy/assets/82761814/a1b8c71b-a4d8-445c-86cf-6c9f5e05a3c4)
![image](https://github.com/joe-vettek/Fluid-Drawers-Legacy/assets/82761814/06907ef4-12bb-4f25-b8b3-1f8c13cc665a)

**Comment by joe-vettek** [comment]
In these two versions, I have done some refactoring work on the bottom layer to solve some stubborn problems.

**Comment by mcm** [comment]
Just tested 4.1.7 and it seems like everything I've had an issue with is working great, except the Jade popup... that still shows "Uncraftable Potion" when looking at the controller slave. Even the thing I forgot to mention - I wasn't able to pull specific fluids from the network using smart pipes - is working!

**Comment by joe-vettek** [comment]
It sounds a bit strange, I will look at it later.

**Comment by joe-vettek** [comment]
Awkward Potion and Potion of Strength....I'm not sure how you get that in there. .

**Comment by joe-vettek** [comment]
ok, the issue is solved. The reason is that I don't know some of Jade's custom settings, so I got stuck.

**Comment by mcm** [comment]
Thank you again for all of the work on this, you're amazing!

Just in case it's helpful in the future - Create lets you craft potions mechanically, and those fluids can get then get pumped around like water and lava. I'm using the drawers as part of a big factory that involves brewing potions, so that's why and how those are in there.

**Comment by joe-vettek** [comment]
Thanks for testing too.
![image](https://github.com/joe-vettek/Fluid-Drawers-Legacy/assets/82761814/ea8f1349-ebfc-4ab3-bf81-e796df787d73)
And recently a modular plugin was made, so in the new version, potions can also be poured directly into the drawer.
